# This is to test some string manipulation

print("Concatenation")
print("This is one " + "this is two")
print(" ")
print("Repeat a string 5 times")
print("This is a string, " * 5)
print(" ")
print("Find out the length with len(string)")
print(len("This string has several characters"))
print(" ")
print("Find a substrings index num within a string with string.find(substring)")
print("This string has several characters".find("string"))
print(" ")
print("Split a string with string.split(value)")
print("This string is split, at with the comma in the middle.".split(","))
print(" ")
print("Strip the string of value string.strip(value)")
print("    This string has a lot of spaces at beginning and end.    ".strip(" "))
print(" ")
print("Method 'isupper' tells if string is all upper value string.isupper()")
print("THIS IS ALL UPPER CASE".isupper())
print("This is NOT all upper case".isupper())
print(" ")
print("Method 'lower' and 'upper' converts strings to all lower or upper case string.lower() string.upper()")
print("THIS WAS MADE LOWER CASE USING LOWER()".lower())
print("this was made upper case using upper()".upper())
print(" ")
