
out_file = open('C:/Users/ak75/Documents/Python/introductionToPython3.5/lesson10/practicePrograms/mydata.txt', 'w')

out_file.write('Hello ')
out_file.write('World!')
out_file.write('\n')
weekends = ['Saturday', 'Sunday']
out_file.writelines(weekends)
out_file.write('\n')
out_file.writelines(weekends)
out_file.flush()
out_file.close()

out_file = open('C:/Users/ak75/Documents/Python/introductionToPython3.5/lesson10/practicePrograms/mydata.txt', 'a')
out_file.write('\n')
out_file.writelines(weekends)
out_file.write('\n')
out_file.writelines(weekends)
out_file.write('\n')
out_file.writelines(weekends)
out_file.write('\n')
out_file.writelines(weekends)
out_file.flush()
out_file.close()

test_file = open('C:/Users/ak75/Documents/Python/introductionToPython3.5/lesson10/practicePrograms/test.txt', 'w')
test_file.write('First line')
test_file.write('\n')
test_file.write('Second line')
test_file.flush()
test_file.close()

in_file = open('C:/Users/ak75/Documents/Python/introductionToPython3.5/lesson10/practicePrograms/mydata.txt', 'r')

first = in_file.read(2)
second = in_file.read()
print(first, second)
print("-" * 30)
new_in_file = open('C:/Users/ak75/Documents/Python/introductionToPython3.5/lesson10/practicePrograms/mydata.txt', 'r')
first_line = new_in_file.readlines()
print(first_line)
in_file.close()

test_file = open('C:/Users/ak75/Documents/Python/introductionToPython3.5/lesson10/practicePrograms/test.txt', 'r')
print(test_file.readlines())
test_file.close()
