in_file = open('C:/Users/ak75/Documents/Python/introductionToPython3.5/lesson10/practicePrograms/mydata2.txt', 'r+')

print (in_file.readline())
print (in_file.tell())
in_file.seek(0)
print (in_file.readline())
print (in_file.tell())
in_file.seek(0)
in_file.write('Hi!')
in_file.seek(0)
print (in_file.readline())